name: 'dbt_kanoniv'
version: '0.1.0'
config-version: 2

require-dbt-version: [">=1.3.0", "<2.0.0"]

profile: 'kanoniv'

model-paths: ["models"]
macro-paths: ["macros"]
seed-paths: ["seeds"]

clean-targets:
  - "target"
  - "dbt_packages"

dispatch:
  - macro_namespace: dbt_kanoniv
    search_order: ['dbt_kanoniv', 'dbt']

vars:
  # Normalization options
  kanoniv_default_country: 'US'
  kanoniv_email_normalize_gmail: true

  # Model enablement — set to true in your project to materialise Kanoniv models
  kanoniv_enable_models: false

  # Source configuration — override these to match your schema
  kanoniv_database: null
  kanoniv_schema: 'public'
  kanoniv_external_entities_table: 'external_entities'
  kanoniv_canonical_entities_table: 'canonical_entities'
  kanoniv_identity_links_table: 'identity_links'
  kanoniv_match_results_table: 'match_results'
  kanoniv_data_sources_table: 'data_sources'
  kanoniv_batch_runs_table: 'batch_runs'

models:
  dbt_kanoniv:
    +enabled: "{{ var('kanoniv_enable_models', false) }}"
    staging:
      +materialized: view
    intermediate:
      +materialized: view
    marts:
      +materialized: table
